name: CD-aws
'on':
  workflow_dispatch: null
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      
    steps:
      - uses: actions/checkout@v2
   
      - name: Connecting GitHub Actions To AWS Using OIDC - Roles
        uses: aws-actions/configure-aws-credentials@master
        with:
         role-to-assume: arn:aws:iam::876955837174:role/github
         role-session-name: github-actions-session
         aws-region: us-east-1
      - run: aws sts get-caller-identity
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest    
      - name: Packer Init #- Branches
        run: "packer init ./mypacker.json.pkr.hcl"
  
      - name: Packer Build #- Branches
        run: "packer build ./mypacker.json.pkr.hcl"
        
      - name: Terraform Apply
        env:
          TF_VAR_ec2_name: "${{ github.event.inputs.ec2-name }}"
        run: |
         cd module/
         terraform init
         terraform validate
         terraform plan
         terraform apply -auto-approve
        
      
